package main

const warmupTemplateText = `// Code generated by warmup; DO NOT EDIT.
package main

import (
{{- range .Imports }}
	{{ .Alias }} "{{ .Path }}"
{{- end }}
)

func init() {
{{- range .WarmupCalls }}
	reflecting.GetFunctionName({{ .Expr }}) // from {{ join .Comments ", " }}
{{- end }}
}`
