package main

const warmupTemplateText = `// Code generated by warmup_gen.go; DO NOT EDIT.
// Code generated by warmup_gen.go; DO NOT EDIT.
// Code generated by warmup_gen.go; DO NOT EDIT.

package {{.PackageName}}

import (
{{- range .Imports }}
	{{ .Alias }} "{{ .Path }}"
{{- end }}
	"github.com/BetaGoRobot/go_utils/reflecting"
)

func init() {
{{- range .WarmupCalls }}
	reflecting.GetFunctionName({{ .Expr }}) // from {{ join .Comments ", " }}
{{- end }}
}
`
